### PR TITLE
added 3 files

### PR DESCRIPTION
**Pull request by nikoders5**

### CODE REVIEW

**Comment by iamthebj** [comment]
GIT ASSIST PREDICTION : Rejected due to syntax error

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected Due To 6 syntax error

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files:['niki3.py']

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files:['niki1.py', 'niki1.py', 'niki2.py', 'niki3.py', 'niki2.py', 'niki3.py']

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files:['niki1.py', 'niki1.py', 'niki2.py', 'niki3.py', 'niki2.py', 'niki3.py']

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files:['niki1.py', 'niki2.py', 'niki3.py']

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files:niki1.py ,niki2.py ,niki3.py

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py,niki2.py,niki3.py.

**Comment by iamthebj** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
niki3.py-7-1- E265 block comment should start with '# '
niki3.py-9-12- E225 missing whitespace around operator
niki3.py-11-1- E122 continuation line missing indentation or outdented
niki3.py-12-1- E122 continuation line missing indentation or outdented
niki3.py-14-1- E122 continuation line missing indentation or outdented
niki3.py-17-1- E112 expected an indented block
niki3.py-17-17- E231 missing whitespace after ','
niki3.py-18-8- E111 indentation is not a multiple of four
niki3.py-18-8- E117 over-indented
niki3.py-19-4- E901 IndentationError- unindent does not match any outer indentation level

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected. Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
No syntax error found in any file.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Comment by GithubPrediction** [comment]
Git Assist Prediction: To Be Rejected.Syntax Errors found in the following files: niki1.py, niki2.py, niki3.py.

**Pull request closed without merging**
